name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Install dependencies
        run:  npm ci  # Run npm install to install dependencies

      - name: Run tests
        run: npm test  # Run your test script
